version: '2'
services:
  web:
    build: .
    volumes:
      - .:/upaya
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: "redis://redis"
      DATABASE_URL: "postgres://postgres@db"
    depends_on:
      - db
      - redis
  sidekiq:
    build: .
    command: "bundle exec sidekiq --config config/sidekiq.yml"
    environment:
      REDIS_URL: "redis://redis"
      DATABASE_URL: "postgres://postgres@db"
      SMTP_HOST: "mailcatcher"
    depends_on:
      - db
      - redis
      - mailcatcher
    volumes:
      - .:/upaya
  db:
    image: postgres
  redis:
    image: redis
  mailcatcher:
    image: rordi/docker-mailcatcher
    container_name: mailcatcher
    ports:
      - 1080:1080
