development:
  "LGCBPFY190002 Order 3":
    iaa_gtc: LGCBPFY190002
    order_number: 3
    mod_number: 0
    start_date: "2020-02-15"
    end_date: "2021-02-14"
    estimated_amount: 1_181_292.21
    pricing_model: 2
    iaa_status: active
    approved_apps:
      - "Foo"
      - "Bar"
      - "Baz"
    integrations:
      - "https://rp1.serviceprovider.com/auth/saml/metadata"

  "LGTTSFY190003 Order 2":
    iaa_gtc: LGTTSFY190003
    order_number: 2
    mod_number: 1
    start_date: "2020-05-01"
    end_date: "2021-04-31"
    estimated_amount: 959_839.12
    pricing_model: 3
    iaa_status: active
    approved_apps:
      - "One app"
      - "Another app"
    integrations:
      - "urn:gov:gsa:SAML:2.0.profiles:sp:sso:localhost"

test:
  "LGCBPFY190002 Order 3":
    iaa_gtc: LGCBPFY190002
    order_number: 3
    mod_number: 0
    start_date: "2020-02-15"
    end_date: "2021-02-14"
    estimated_amount: 1_181_292.21
    pricing_model: 2
    iaa_status: active
    approved_apps:
      - "Foo"
      - "Bar"
      - "Baz"
    integrations:
      - "https://rp1.serviceprovider.com/auth/saml/metadata"

  "LGTTSFY190003 Order 2":
    iaa_gtc: LGTTSFY190003
    order_number: 2
    mod_number: 1
    start_date: "2020-05-01"
    end_date: "2021-04-31"
    estimated_amount: 959_839.12
    pricing_model: 3
    iaa_status: active
    approved_apps:
      - "One app"
      - "Another app"
    integrations:
      - "https://aal3.serviceprovider.com/auth/saml/metadata"
