- doc_auth.buttons.take_or_upload_picture
- doc_auth.buttons.take_picture
- doc_auth.buttons.take_picture_retry
- doc_auth.buttons.upload_picture
- doc_auth.forms.change_file
- doc_auth.forms.choose_file_html
- doc_auth.forms.selected_file
- doc_auth.headings.back
- doc_auth.headings.document_capture
- doc_auth.headings.document_capture_back
- doc_auth.headings.document_capture_front
- doc_auth.headings.document_capture_selfie
- doc_auth.headings.front
- doc_auth.headings.interstitial
- doc_auth.headings.photo
- doc_auth.headings.selfie
- doc_auth.info.document_capture_intro_acknowledgment
- doc_auth.info.interstitial_eta
- doc_auth.info.interstitial_thanks
- doc_auth.instructions.document_capture_selfie_consent_banner
- doc_auth.instructions.document_capture_selfie_consent_blocked
- doc_auth.instructions.document_capture_selfie_consent_reason
- doc_auth.instructions.document_capture_selfie_instructions
- doc_auth.tips.document_capture_header_text
- doc_auth.tips.document_capture_hint
- doc_auth.tips.document_capture_id_text1
- doc_auth.tips.document_capture_id_text2
- doc_auth.tips.document_capture_id_text3
- doc_auth.tips.document_capture_id_text4
- doc_auth.tips.document_capture_selfie_text1
- doc_auth.tips.document_capture_selfie_text2
- doc_auth.tips.document_capture_selfie_text3
- errors.doc_auth.acuant_network_error
- errors.doc_auth.document_capture_selfie_consent_blocked
- errors.doc_auth.photo_blurry
- errors.doc_auth.photo_file_size
- errors.doc_auth.photo_glare
- errors.doc_auth.selfie
- errors.messages.format_mismatch
- errors.messages.missing_field
- forms.buttons.continue
- forms.buttons.submit.default
- forms.passwords.show
- idv.errors.pattern_mismatch.dob
- idv.errors.pattern_mismatch.personal_key
- idv.errors.pattern_mismatch.ssn
- idv.errors.pattern_mismatch.state_id_number
- idv.errors.pattern_mismatch.zipcode
- idv.failure.button.warning
- idv.messages.jurisdiction.no_id
- instructions.password.strength.i
- instructions.password.strength.ii
- instructions.password.strength.iii
- instructions.password.strength.iv
- instructions.password.strength.v
- simple_form.required.text
- two_factor_authentication.otp_delivery_preference.instruction
- two_factor_authentication.otp_delivery_preference.phone_unsupported
- users.personal_key.close
- valid_email.validations.email.invalid
- zxcvbn.feedback.a_word_by_itself_is_easy_to_guess
- zxcvbn.feedback.add_another_word_or_two_uncommon_words_are_better
- zxcvbn.feedback.all_uppercase_is_almost_as_easy_to_guess_as_all_lowercase
- zxcvbn.feedback.avoid_dates_and_years_that_are_associated_with_you
- zxcvbn.feedback.avoid_recent_years
- zxcvbn.feedback.avoid_repeated_words_and_characters
- zxcvbn.feedback.avoid_sequences
- zxcvbn.feedback.avoid_years_that_are_associated_with_you
- zxcvbn.feedback.capitalization_doesnt_help_very_much
- zxcvbn.feedback.common_names_and_surnames_are_easy_to_guess
- zxcvbn.feedback.dates_are_often_easy_to_guess
- zxcvbn.feedback.for_a_stronger_password_use_a_few_words_separated_by_spaces_but_avoid_common_phrases
- zxcvbn.feedback.names_and_surnames_by_themselves_are_easy_to_guess
- zxcvbn.feedback.predictable_substitutions_like__instead_of_a_dont_help_very_much
- zxcvbn.feedback.recent_years_are_easy_to_guess
- zxcvbn.feedback.repeats_like_aaa_are_easy_to_guess
- zxcvbn.feedback.repeats_like_abcabcabc_are_only_slightly_harder_to_guess_than_abc
- zxcvbn.feedback.reversed_words_arent_much_harder_to_guess
- zxcvbn.feedback.sequences_like_abc_or_6543_are_easy_to_guess
- zxcvbn.feedback.short_keyboard_patterns_are_easy_to_guess
- zxcvbn.feedback.straight_rows_of_keys_are_easy_to_guess
- zxcvbn.feedback.there_is_no_need_for_symbols_digits_or_uppercase_letters
- zxcvbn.feedback.this_is_a_top_100_common_password
- zxcvbn.feedback.this_is_a_top_10_common_password
- zxcvbn.feedback.this_is_a_very_common_password
- zxcvbn.feedback.this_is_similar_to_a_commonly_used_password
- zxcvbn.feedback.use_a_longer_keyboard_pattern_with_more_turns
