AE:
  supports_voice: true
  supports_voice_unconfirmed: false
AO:
  country_code: '244'
  name: Angola
  supports_sms: true
  supports_voice: false
AR:
  supports_voice: false
AS:
  country_code: '1684'
  name: American Samoa
  supports_sms: false
  supports_voice: false
AT:
  supports_voice: false
AU:
  supports_voice: false
BB:
  supports_voice: false
BF:
  supports_voice: false
BG:
  supports_voice: false
BH:
  supports_voice: false
BI:
  country_code: '257'
  name: Burundi
  supports_sms: true
  supports_voice: false
BJ:
  country_code: '229'
  name: Benin
  supports_sms: true
  supports_voice: false
BR:
  supports_voice: false
BY:
  supports_voice: true
  supports_voice_unconfirmed: false
CA:
  supports_voice: false
CH:
  supports_voice: false
CL:
  supports_voice: false
CO:
  supports_voice: false
CY:
  supports_voice: false
DE:
  supports_voice: false
DO:
  supports_voice: false
DZ:
  country_code: '213'
  name: Algeria
  supports_sms: false # Temporarily disabled due to SMS fraud attack 2021-04-16
  supports_voice: false
EC:
  supports_voice: false
EG:
  supports_voice: true
FI:
  supports_voice: false
GB:
  supports_voice: false
GD:
  supports_voice: false
GQ:
  name: Equatorial Guinea
GR:
  supports_voice: false
GT:
  supports_voice: false
HR:
  supports_voice: false
HU:
  supports_voice: false
ID:
  supports_voice: false
IE:
  supports_voice: false
IL:
  supports_voice: false
IQ:
  supports_sms_unconfirmed: false
IS:
  supports_voice: false
IT:
  supports_voice: false
JM:
  supports_voice: false
JO:
  supports_voice: true
  supports_voice_unconfirmed: false
JP:
  supports_voice: false
KE:
  supports_voice: false
KH:
  supports_voice: false
KI:
  country_code: '686'
  name: Kiribati
  supports_sms: true
  supports_voice: false
KW:
  supports_voice: true
  supports_voice_unconfirmed: false
KY:
  supports_voice: false
KZ:
  supports_voice: false
LT:
  supports_voice: false
LU:
  supports_voice: false
LV:
  supports_sms: true
  supports_voice: false
MD:
  supports_voice: false
ML:
  supports_voice: false
MP:
  country_code: '1'
  name: Northern Mariana Islands
  supports_sms: false
  supports_voice: true
MX:
  supports_voice: false
MY:
  supports_voice: false
NI:
  supports_voice: false
'NO':
  supports_voice: false
NZ:
  supports_voice: false
PA:
  supports_voice: false
PE:
  supports_voice: false
PH:
  supports_voice_unconfirmed: false
PK:
  supports_voice: false
PL:
  supports_voice: false
PR:
  supports_voice: false
PW:
  country_code: '680'
  name: Palau
  supports_sms: true
  supports_voice: false
QA:
  supports_voice: true
  supports_voice_unconfirmed: false
RO:
  supports_voice: false
RU:
  supports_voice: true
  supports_voice_unconfirmed: false
SA:
  supports_voice: true
  supports_voice_unconfirmed: false
SI:
  supports_voice: false
SK:
  supports_voice: false
SV:
  supports_voice: false
TD:
  country_code: '235'
  name: Chad
  supports_sms: true
  supports_voice: false
TH:
  supports_voice_unconfirmed: false
TJ:
  supports_voice: false
TL:
  supports_sms: false
TT:
  supports_voice: false
TW:
  supports_voice: false
UY:
  supports_voice: false
VC:
  country_code: '1784'
  name: Saint Vincent and the Grenadines
  supports_sms: true
  supports_voice: false
VE:
  supports_voice: false
VN:
  supports_voice_unconfirmed: false
ZA:
  supports_voice: false
